name: madina_tent_service
publish_to: "none"
version: 2.0.0+2
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  share_plus: ^11.0.0
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
